# Generated by Django 2.1.5 on 2019-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
