# Generated by Django 2.1.5 on 2019-01-23 07:10

import base_user.tools.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_myuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_user_profile_photo_file_name),
        ),
    ]
